modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="saint_louis_bizzare_adventure_"
version="1.0.0"
displayName="Saint Louis Bizzare adventure 1"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="lecoo, MCreator"

[[dependencies.saint_louis_bizzare_adventure_]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




